import localFont from "next/font/local";
import "./globals.css";
import { NavbarWrapper } from "./components/NavbarWrapper";
import ToasterMessage from "./components/ToasterMessage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarWrapper />
        <ToasterMessage />
        <main
          className="bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-white 
  dark:bg-gradient-to-r dark:from-indigo-900 dark:to-purple-900 dark:text-gray-300 
  dark:transition-all dark:duration-500 dark:ease-in-out"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
